EnvironmentConfigurationMetadata:
  Description: 'Assumption: you have created default VPC.

    Java11 + spring + postgresql full working setup. '
  DateCreated: '1599593386000'
  DateModified: '1599593386000'
Platform:
  PlatformArn: arn:aws:elasticbeanstalk:eu-central-1::platform/Corretto 11 running on 64bit Amazon Linux 2/3.1.1
OptionSettings:
  aws:elasticbeanstalk:application:environment:
    SERVER_PORT: '5000'
    RDS_HOSTNAME: ''
    RDS_PASSWORD: postgres
    RDS_PORT: ''
    SPRING_PROFILES_ACTIVE: prod
    RDS_DB_NAME: pw_2020
    RDS_USERNAME: postgres
  aws:elasticbeanstalk:environment:
    ServiceRole: arn:aws:iam::096809033369:role/aws-elasticbeanstalk-service-role
    EnvironmentType: SingleInstance
  aws:elasticbeanstalk:healthreporting:system:
    ConfigDocument:
      Version: 1
      CloudWatchMetrics:
        Instance:
          RootFilesystemUtil: null
          CPUIrq: null
          LoadAverage5min: null
          ApplicationRequests5xx: null
          ApplicationRequests4xx: null
          CPUUser: null
          LoadAverage1min: null
          ApplicationLatencyP50: null
          CPUIdle: null
          InstanceHealth: null
          ApplicationLatencyP95: null
          ApplicationLatencyP85: null
          ApplicationLatencyP90: null
          CPUSystem: null
          ApplicationLatencyP75: null
          CPUSoftirq: null
          ApplicationLatencyP10: null
          ApplicationLatencyP99: null
          ApplicationRequestsTotal: null
          ApplicationLatencyP99.9: null
          ApplicationRequests3xx: null
          ApplicationRequests2xx: null
          CPUIowait: null
          CPUNice: null
        Environment:
          InstancesSevere: null
          InstancesDegraded: null
          ApplicationRequests5xx: null
          ApplicationRequests4xx: null
          ApplicationLatencyP50: null
          ApplicationLatencyP95: null
          ApplicationLatencyP85: null
          InstancesUnknown: null
          ApplicationLatencyP90: null
          InstancesInfo: null
          InstancesPending: null
          ApplicationLatencyP75: null
          ApplicationLatencyP10: null
          ApplicationLatencyP99: null
          ApplicationRequestsTotal: null
          InstancesNoData: null
          ApplicationLatencyP99.9: null
          ApplicationRequests3xx: null
          ApplicationRequests2xx: null
          InstancesOk: null
          InstancesWarning: null
      Rules:
        Environment:
          ELB:
            ELBRequests4xx:
              Enabled: true
          Application:
            ApplicationRequests4xx:
              Enabled: true
  aws:autoscaling:launchconfiguration:
    IamInstanceProfile: aws-elasticbeanstalk-ec2-role
  aws:rds:dbinstance:
    DBPassword: postgres
    DBEngine: postgres
    DBUser: postgres
    DBDeletionPolicy: Snapshot
  aws:elasticbeanstalk:managedactions:
    ManagedActionsEnabled: true
    PreferredStartTime: Sun:06:00
  aws:elasticbeanstalk:managedactions:platformupdate:
    UpdateLevel: minor
EnvironmentTier:
  Type: Standard
  Name: WebServer
Extensions:
  RDS.EBConsoleSnippet:
    Order: null
    SourceLocation: https://s3.eu-central-1.amazonaws.com/elasticbeanstalk-env-resources-eu-central-1/eb_snippets/rds/rds.json
AWSConfigurationTemplateVersion: 1.1.0.0
